//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenjoyHR.Models.ED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absent
    {
        public int Id { get; set; }
        public int absentnameid { get; set; }
        public string absentreason { get; set; }
        public string absentremarks { get; set; }
        public System.DateTime absentnowtime { get; set; }
    }
}
