//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenjoyHR.Models.ED
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeesEntities : DbContext
    {
        public EmployeesEntities()
            : base("name=EmployeesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HR> HRs { get; set; }
        public virtual DbSet<Absent> Absents { get; set; }
        public virtual DbSet<Caution> Cautions { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<Loss> Losses { get; set; }
        public virtual DbSet<Performance> Performances { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
