//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenjoyHR.Models.ED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int Id { get; set; }
        public int loadnameid { get; set; }
        public string loanamount { get; set; }
        public string loanperiod { get; set; }
        public string loanreaason { get; set; }
        public string loanremarks { get; set; }
        public System.DateTime loandatenow { get; set; }
    }
}
