//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenjoyHR.Models.ED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public int Id { get; set; }
        public int nameid { get; set; }
        public string grading { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Pdatenow { get; set; }
    }
}
