//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenjoyHR.Models.ED
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int Id { get; set; }
        public int promonameid { get; set; }
        public string promoto { get; set; }
        public string promofrom { get; set; }
        public System.DateTime promotodate { get; set; }
        public System.DateTime promodatenow { get; set; }
    }
}
